// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: receipt.proto

package com.toasttab.receipts;

public final class ReceiptProtos {
  private ReceiptProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReceiptOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Receipt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Line header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.Line header = 1;</code>
     * @return The header.
     */
    com.toasttab.receipts.LineProtos.Line getHeader();
    /**
     * <code>.Line header = 1;</code>
     */
    com.toasttab.receipts.LineProtos.LineOrBuilder getHeaderOrBuilder();

    /**
     * <code>.Line content = 2;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <code>.Line content = 2;</code>
     * @return The content.
     */
    com.toasttab.receipts.LineProtos.Line getContent();
    /**
     * <code>.Line content = 2;</code>
     */
    com.toasttab.receipts.LineProtos.LineOrBuilder getContentOrBuilder();

    /**
     * <code>.Line footer = 3;</code>
     * @return Whether the footer field is set.
     */
    boolean hasFooter();
    /**
     * <code>.Line footer = 3;</code>
     * @return The footer.
     */
    com.toasttab.receipts.LineProtos.Line getFooter();
    /**
     * <code>.Line footer = 3;</code>
     */
    com.toasttab.receipts.LineProtos.LineOrBuilder getFooterOrBuilder();
  }
  /**
   * Protobuf type {@code Receipt}
   */
  public  static final class Receipt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Receipt)
      ReceiptOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Receipt.newBuilder() to construct.
    private Receipt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Receipt() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Receipt();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Receipt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.toasttab.receipts.LineProtos.Line.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.toasttab.receipts.LineProtos.Line.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.toasttab.receipts.LineProtos.Line.Builder subBuilder = null;
              if (content_ != null) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(com.toasttab.receipts.LineProtos.Line.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.toasttab.receipts.LineProtos.Line.Builder subBuilder = null;
              if (footer_ != null) {
                subBuilder = footer_.toBuilder();
              }
              footer_ = input.readMessage(com.toasttab.receipts.LineProtos.Line.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(footer_);
                footer_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReceiptProtos.internal_static_Receipt_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReceiptProtos.internal_static_Receipt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Receipt.class, Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.toasttab.receipts.LineProtos.Line header_;
    /**
     * <code>.Line header = 1;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.Line header = 1;</code>
     * @return The header.
     */
    public com.toasttab.receipts.LineProtos.Line getHeader() {
      return header_ == null ? com.toasttab.receipts.LineProtos.Line.getDefaultInstance() : header_;
    }
    /**
     * <code>.Line header = 1;</code>
     */
    public com.toasttab.receipts.LineProtos.LineOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.toasttab.receipts.LineProtos.Line content_;
    /**
     * <code>.Line content = 2;</code>
     * @return Whether the content field is set.
     */
    public boolean hasContent() {
      return content_ != null;
    }
    /**
     * <code>.Line content = 2;</code>
     * @return The content.
     */
    public com.toasttab.receipts.LineProtos.Line getContent() {
      return content_ == null ? com.toasttab.receipts.LineProtos.Line.getDefaultInstance() : content_;
    }
    /**
     * <code>.Line content = 2;</code>
     */
    public com.toasttab.receipts.LineProtos.LineOrBuilder getContentOrBuilder() {
      return getContent();
    }

    public static final int FOOTER_FIELD_NUMBER = 3;
    private com.toasttab.receipts.LineProtos.Line footer_;
    /**
     * <code>.Line footer = 3;</code>
     * @return Whether the footer field is set.
     */
    public boolean hasFooter() {
      return footer_ != null;
    }
    /**
     * <code>.Line footer = 3;</code>
     * @return The footer.
     */
    public com.toasttab.receipts.LineProtos.Line getFooter() {
      return footer_ == null ? com.toasttab.receipts.LineProtos.Line.getDefaultInstance() : footer_;
    }
    /**
     * <code>.Line footer = 3;</code>
     */
    public com.toasttab.receipts.LineProtos.LineOrBuilder getFooterOrBuilder() {
      return getFooter();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (content_ != null) {
        output.writeMessage(2, getContent());
      }
      if (footer_ != null) {
        output.writeMessage(3, getFooter());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (content_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getContent());
      }
      if (footer_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getFooter());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Receipt)) {
        return super.equals(obj);
      }
      Receipt other = (Receipt) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (hasFooter() != other.hasFooter()) return false;
      if (hasFooter()) {
        if (!getFooter()
            .equals(other.getFooter())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasFooter()) {
        hash = (37 * hash) + FOOTER_FIELD_NUMBER;
        hash = (53 * hash) + getFooter().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Receipt parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Receipt parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Receipt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Receipt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Receipt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Receipt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Receipt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Receipt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Receipt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Receipt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Receipt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Receipt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Receipt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Receipt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Receipt)
        ReceiptOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReceiptProtos.internal_static_Receipt_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReceiptProtos.internal_static_Receipt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Receipt.class, Builder.class);
      }

      // Construct using com.toasttab.receipts.ReceiptProtos.Receipt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (contentBuilder_ == null) {
          content_ = null;
        } else {
          content_ = null;
          contentBuilder_ = null;
        }
        if (footerBuilder_ == null) {
          footer_ = null;
        } else {
          footer_ = null;
          footerBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReceiptProtos.internal_static_Receipt_descriptor;
      }

      @Override
      public Receipt getDefaultInstanceForType() {
        return Receipt.getDefaultInstance();
      }

      @Override
      public Receipt build() {
        Receipt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Receipt buildPartial() {
        Receipt result = new Receipt(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        if (footerBuilder_ == null) {
          result.footer_ = footer_;
        } else {
          result.footer_ = footerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Receipt) {
          return mergeFrom((Receipt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Receipt other) {
        if (other == Receipt.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        if (other.hasFooter()) {
          mergeFooter(other.getFooter());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Receipt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Receipt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.toasttab.receipts.LineProtos.Line header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.toasttab.receipts.LineProtos.Line, com.toasttab.receipts.LineProtos.Line.Builder, com.toasttab.receipts.LineProtos.LineOrBuilder> headerBuilder_;
      /**
       * <code>.Line header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.Line header = 1;</code>
       * @return The header.
       */
      public com.toasttab.receipts.LineProtos.Line getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.toasttab.receipts.LineProtos.Line.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.Line header = 1;</code>
       */
      public Builder setHeader(com.toasttab.receipts.LineProtos.Line value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Line header = 1;</code>
       */
      public Builder setHeader(
          com.toasttab.receipts.LineProtos.Line.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Line header = 1;</code>
       */
      public Builder mergeHeader(com.toasttab.receipts.LineProtos.Line value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.toasttab.receipts.LineProtos.Line.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Line header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Line header = 1;</code>
       */
      public com.toasttab.receipts.LineProtos.Line.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.Line header = 1;</code>
       */
      public com.toasttab.receipts.LineProtos.LineOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.toasttab.receipts.LineProtos.Line.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.Line header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.toasttab.receipts.LineProtos.Line, com.toasttab.receipts.LineProtos.Line.Builder, com.toasttab.receipts.LineProtos.LineOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.toasttab.receipts.LineProtos.Line, com.toasttab.receipts.LineProtos.Line.Builder, com.toasttab.receipts.LineProtos.LineOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.toasttab.receipts.LineProtos.Line content_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.toasttab.receipts.LineProtos.Line, com.toasttab.receipts.LineProtos.Line.Builder, com.toasttab.receipts.LineProtos.LineOrBuilder> contentBuilder_;
      /**
       * <code>.Line content = 2;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return contentBuilder_ != null || content_ != null;
      }
      /**
       * <code>.Line content = 2;</code>
       * @return The content.
       */
      public com.toasttab.receipts.LineProtos.Line getContent() {
        if (contentBuilder_ == null) {
          return content_ == null ? com.toasttab.receipts.LineProtos.Line.getDefaultInstance() : content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>.Line content = 2;</code>
       */
      public Builder setContent(com.toasttab.receipts.LineProtos.Line value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Line content = 2;</code>
       */
      public Builder setContent(
          com.toasttab.receipts.LineProtos.Line.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Line content = 2;</code>
       */
      public Builder mergeContent(com.toasttab.receipts.LineProtos.Line value) {
        if (contentBuilder_ == null) {
          if (content_ != null) {
            content_ =
              com.toasttab.receipts.LineProtos.Line.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Line content = 2;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = null;
          onChanged();
        } else {
          content_ = null;
          contentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Line content = 2;</code>
       */
      public com.toasttab.receipts.LineProtos.Line.Builder getContentBuilder() {
        
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>.Line content = 2;</code>
       */
      public com.toasttab.receipts.LineProtos.LineOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_ == null ?
              com.toasttab.receipts.LineProtos.Line.getDefaultInstance() : content_;
        }
      }
      /**
       * <code>.Line content = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.toasttab.receipts.LineProtos.Line, com.toasttab.receipts.LineProtos.Line.Builder, com.toasttab.receipts.LineProtos.LineOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.toasttab.receipts.LineProtos.Line, com.toasttab.receipts.LineProtos.Line.Builder, com.toasttab.receipts.LineProtos.LineOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      private com.toasttab.receipts.LineProtos.Line footer_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.toasttab.receipts.LineProtos.Line, com.toasttab.receipts.LineProtos.Line.Builder, com.toasttab.receipts.LineProtos.LineOrBuilder> footerBuilder_;
      /**
       * <code>.Line footer = 3;</code>
       * @return Whether the footer field is set.
       */
      public boolean hasFooter() {
        return footerBuilder_ != null || footer_ != null;
      }
      /**
       * <code>.Line footer = 3;</code>
       * @return The footer.
       */
      public com.toasttab.receipts.LineProtos.Line getFooter() {
        if (footerBuilder_ == null) {
          return footer_ == null ? com.toasttab.receipts.LineProtos.Line.getDefaultInstance() : footer_;
        } else {
          return footerBuilder_.getMessage();
        }
      }
      /**
       * <code>.Line footer = 3;</code>
       */
      public Builder setFooter(com.toasttab.receipts.LineProtos.Line value) {
        if (footerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          footer_ = value;
          onChanged();
        } else {
          footerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Line footer = 3;</code>
       */
      public Builder setFooter(
          com.toasttab.receipts.LineProtos.Line.Builder builderForValue) {
        if (footerBuilder_ == null) {
          footer_ = builderForValue.build();
          onChanged();
        } else {
          footerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Line footer = 3;</code>
       */
      public Builder mergeFooter(com.toasttab.receipts.LineProtos.Line value) {
        if (footerBuilder_ == null) {
          if (footer_ != null) {
            footer_ =
              com.toasttab.receipts.LineProtos.Line.newBuilder(footer_).mergeFrom(value).buildPartial();
          } else {
            footer_ = value;
          }
          onChanged();
        } else {
          footerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Line footer = 3;</code>
       */
      public Builder clearFooter() {
        if (footerBuilder_ == null) {
          footer_ = null;
          onChanged();
        } else {
          footer_ = null;
          footerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Line footer = 3;</code>
       */
      public com.toasttab.receipts.LineProtos.Line.Builder getFooterBuilder() {
        
        onChanged();
        return getFooterFieldBuilder().getBuilder();
      }
      /**
       * <code>.Line footer = 3;</code>
       */
      public com.toasttab.receipts.LineProtos.LineOrBuilder getFooterOrBuilder() {
        if (footerBuilder_ != null) {
          return footerBuilder_.getMessageOrBuilder();
        } else {
          return footer_ == null ?
              com.toasttab.receipts.LineProtos.Line.getDefaultInstance() : footer_;
        }
      }
      /**
       * <code>.Line footer = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.toasttab.receipts.LineProtos.Line, com.toasttab.receipts.LineProtos.Line.Builder, com.toasttab.receipts.LineProtos.LineOrBuilder> 
          getFooterFieldBuilder() {
        if (footerBuilder_ == null) {
          footerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.toasttab.receipts.LineProtos.Line, com.toasttab.receipts.LineProtos.Line.Builder, com.toasttab.receipts.LineProtos.LineOrBuilder>(
                  getFooter(),
                  getParentForChildren(),
                  isClean());
          footer_ = null;
        }
        return footerBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Receipt)
    }

    // @@protoc_insertion_point(class_scope:Receipt)
    private static final Receipt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Receipt();
    }

    public static Receipt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Receipt>
        PARSER = new com.google.protobuf.AbstractParser<Receipt>() {
      @Override
      public Receipt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Receipt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Receipt> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Receipt> getParserForType() {
      return PARSER;
    }

    @Override
    public Receipt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Receipt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Receipt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rreceipt.proto\032\nline.proto\"O\n\007Receipt\022\025" +
      "\n\006header\030\001 \001(\0132\005.Line\022\026\n\007content\030\002 \001(\0132\005" +
      ".Line\022\025\n\006footer\030\003 \001(\0132\005.LineB&\n\025com.toas" +
      "ttab.receiptsB\rReceiptProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.toasttab.receipts.LineProtos.getDescriptor(),
        });
    internal_static_Receipt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Receipt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Receipt_descriptor,
        new String[] { "Header", "Content", "Footer", });
    com.toasttab.receipts.LineProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
